name: build_tag

on:
  push:
    tags:
      - '*'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU-action
        uses: docker/setup-qemu-action@v1

      - name: Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Dockerhub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get tag name
        id: build-tag
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build image and push
        uses: docker/build-push-action@v2
        with:
          build-args: |
            SSHI_VERSION=${{ env.TAG_NAME }}
          context: container/.
          platforms: linux/amd64
          push: true
          tags: |
            ronivay/ssh-inscribe:latest
            ronivay/ssh-inscribe:${{ env.TAG_NAME }}
